services:
    kafka:
        image: apache/kafka:latest
        container_name: kafka-broker
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
        restart: always
        volumes:
            - kafka-data:/var/lib/kafka/data
    neo4j:
        container_name: neo4j
        image: neo4j:2025.03-community-bullseye
        ports:
            - "7474:7474"
            - "7687:7687"
        restart: always
        volumes:
            - ~/neo4j/data:/data
        
    mariadb:
        image: mariadb:10.11.11-ubi9
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
            MYSQL_DATABASE: testdb
        restart: always
        networks:
            - mariadb-net
        volumes:
            - mariadb:/var/lib/mysql
            - ~/config/conf.d:/etc/mysql/conf.d
    
    mongo:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASKCAUTH_USERNAME: root
            ME_CONFIG_BASKCAUTH_PASSWORD: example
        depends_on:
            - mongo

networks:
    mariadb-net:
        driver: bridge
volumes:
    kafka-data:
        driver: local
    mariadb:
        driver: local